# Generated by Django 5.0.4 on 2024-05-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdeal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
