# Generated by Django 5.0.4 on 2024-05-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_performer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='proformer_name',
        ),
    ]
